pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        jcenter()
    }
}
rootProject.name = "AndroidCoreBase"
include ':examaple'
include ':core:utils'
include ':core:ui'
include ':core:paginator'
include ':core:view'
include ':core:analytics'

project(':core:ui').projectDir = new File(rootDir, '/ui')
project(':core:view').projectDir = new File(rootDir, '/view')
project(':core:paginator').projectDir = new File(rootDir, '/paginator')
project(':core:utils').projectDir = new File(rootDir, '/utils')
project(':core:analytics').projectDir = new File(rootDir, '/analytics')
